#include "ur_emit.h"

#include <algorithm>
#include <fstream>
#include <iostream>
#include <sstream>
#include <stdexcept>
#include <string>
#include <vector>

#include "backend/codegen.h"
#include "config.h"
#include "frontend/ast.h"
#include "frontend/cse_config.h"
#include "frontend/lexer.h"
#include "frontend/parser.h"
#include "frontend/region_extractor.h"
#include "ir/ir_builder.h"
#include "ir/ir_module.h"
#include "lattice_resolve.h"
#include "passes/pass_manager.h"

namespace cse {
namespace freelb {
namespace {

struct LatSetDef {
  const char* name;
  int d;
  int q;
};

const LatSetDef kLatsets[] = {
    {"D2Q5", 2, 5},   {"D2Q9", 2, 9},   {"D3Q7", 3, 7},
    {"D3Q15", 3, 15}, {"D3Q19", 3, 19}, {"D3Q27", 3, 27},
};

std::string baseName(const std::string& path) {
  size_t slash = path.find_last_of("/\\");
  return slash == std::string::npos ? path : path.substr(slash + 1);
}

// Accept `// @cse`, `//  @cse` and `//@cse` uniformly.
std::string normalizeMarkers(const std::string& src) {
  std::string out;
  out.reserve(src.size());
  std::istringstream iss(src);
  std::string line;
  bool first = true;
  while (std::getline(iss, line)) {
    size_t p = line.find("//");
    if (p != std::string::npos) {
      size_t q = p + 2;
      while (q < line.size() && (line[q] == ' ' || line[q] == '\t')) ++q;
      if (line.compare(q, 4, "@cse") == 0) {
        line = line.substr(0, p) + "//@cse";
      }
    }
    if (!first) out += "\n";
    first = false;
    out += line;
  }
  return out;
}

// Copy the leading C-style license block, if any.
std::string extractLicense(const std::string& src) {
  if (src.size() >= 2 && src[0] == '/' && src[1] == '*') {
    size_t pos = src.find("*/");
    if (pos != std::string::npos) return src.substr(0, pos + 2) + "\n";
  }
  return "";
}

std::string stripModifiers(std::string type) {
  for (;;) {
    if (type.rfind("static ", 0) == 0) {
      type = type.substr(7);
      continue;
    }
    if (type.rfind("inline ", 0) == 0) {
      type = type.substr(7);
      continue;
    }
    break;
  }
  return type;
}

std::string replaceAll(std::string s, const std::string& from,
                       const std::string& to) {
  size_t pos = 0;
  while ((pos = s.find(from, pos)) != std::string::npos) {
    s.replace(pos, from.size(), to);
    pos += to.size();
  }
  return s;
}

std::string emitMethod(const FunctionDef& method, const std::string& body) {
  std::string out;
  out += "  __any__ static " + stripModifiers(method.returnType) + " " +
         method.name + "(";
  for (size_t i = 0; i < method.params.size(); ++i) {
    if (i) out += ", ";
    out += method.params[i].type + " " + method.params[i].name;
  }
  out += "){\n";
  out += body;
  out += "  }\n";
  return out;
}

}  // namespace

UrConfig detectUrConfig(const std::string& inputPath) {
  std::string name = baseName(inputPath);
  UrConfig cfg;
  if (name == "moment.h") {
    cfg.include = "lbm/moment.h";
    cfg.ns = "moment";
  } else if (name == "equilibrium.h") {
    cfg.include = "lbm/equilibrium.h";
    cfg.ns = "equilibrium";
  } else if (name == "force.h") {
    cfg.include = "lbm/force.h";
    cfg.ns = "force";
  } else {
    throw std::runtime_error("unknown input file: " + name);
  }
  return cfg;
}

bool generateUrHeader(const std::string& inputPath,
                      const std::string& outputPath) {
  std::ifstream ifs(inputPath);
  if (!ifs.is_open()) {
    std::cerr << "csegen: cannot open " << inputPath << "\n";
    return false;
  }
  std::string source((std::istreambuf_iterator<char>(ifs)),
                     std::istreambuf_iterator<char>());
  ifs.close();

  UrConfig cfg = detectUrConfig(inputPath);
  std::string normalized = normalizeMarkers(source);
  auto regions = RegionExtractor().extract(normalized);
  if (regions.empty()) {
    std::cerr << "csegen: no // @cse markers in " << inputPath << "\n";
    return false;
  }

  std::string out;
  out += extractLicense(source);
  out += "// " + baseName(outputPath) + " fragment generated by csegen from " +
         cfg.include + "\n";
  out += "#pragma once\n";
  out += "#include \"" + cfg.include + "\"\n";
  out += "#ifdef _UNROLLFOR\n";
  out += "namespace " + cfg.ns + " {\n\n";
  out += "#ifdef __CUDA_ARCH__\n";
  out += "template <typename T, typename LatSet, typename TypePack>\n";
  out += "using CELL = cudev::Cell<T, LatSet, TypePack>;\n";
  out += "#else\n";
  out += "template <typename T, typename LatSet, typename TypePack>\n";
  out += "using CELL = Cell<T, LatSet, TypePack>;\n";
  out += "#endif\n\n";

  int structCount = 0;
  const int latCount = static_cast<int>(sizeof(kLatsets) / sizeof(kLatsets[0]));

  for (const auto& region : regions) {
    CSEConfig parseCfg = createFreeLBConfig();
    Parser::ParseResult parsed;
    try {
      Lexer lexer(region.code, parseCfg);
      std::vector<Token> tokens = lexer.tokenize();
      Parser parser(tokens, parseCfg);
      parsed = parser.parseAll();
    } catch (const std::exception& e) {
      std::cerr << "csegen: parse error: " << e.what() << "\n";
      return false;
    }

    for (const auto& sdPtr : parsed.structDefs) {
      const StructDef& sd = *sdPtr;
      if (sd.templateParams.size() != 1 ||
          sd.templateParams[0].paramName != "CELL") {
        std::cerr << "csegen: skipping unsupported struct " << sd.name << "\n";
        continue;
      }

      for (const auto& lat : kLatsets) {
        CSEConfig cfg2 = createFreeLBConfig();
        cfg2.latsetAlias = "LatSet";
        cfg2.latsetName = lat.name;
        cfg2.latsetDim = lat.d;
        cfg2.latsetQ = lat.q;
        cfg2.latsetCs2 = 1.0 / 3.0;

        std::string spec;
        spec += "template <typename T, typename TypePack>\n";
        spec += "struct " + sd.name + "<CELL<T, " + lat.name + "<T>, TypePack>>{\n";
        spec += "using LatSet = " + std::string(lat.name) + "<T>;\n";

        for (const auto& method : sd.methods) {
          IRModule module;
          IRBuilder builder(&module, cfg2);
          builder.buildFunction(*method);
          auto pm = PassManager::createDefault(cfg2, false,
                                               createLatticeResolvePass(cfg2));
          pm.runAll(module);
          CodeGen codegen;
          std::string body = codegen.generateBody(module, 2);
          body = replaceAll(body, "auto ", "const T ");
          spec += emitMethod(*method, body);
        }
        spec += "};\n\n";
        out += spec;
      }
      structCount++;
    }
  }

  out += "}  // namespace " + cfg.ns + "\n";
  out += "#endif  // _UNROLLFOR\n";

  std::ofstream ofs(outputPath);
  if (!ofs.is_open()) {
    std::cerr << "csegen: cannot write " << outputPath << "\n";
    return false;
  }
  ofs << out;
  std::cout << "csegen: wrote " << outputPath << " (" << structCount
            << " structs x " << latCount << " lattice sets)\n";
  return true;
}

}  // namespace freelb
}  // namespace cse
