// Numerical verification for the generated equilibrium kernel.
// Include the tool output (regenerated by: ./bin/cse equilibrium_d3q19.cpp)
// and compare against a straightforward reference implementation.
#include <cmath>
#include <cstdio>

#include "equilibrium_d3q19.cpp.cse"

namespace {

const int kC[19][3] = {
    {0, 0, 0},   {1, 0, 0},   {-1, 0, 0}, {0, 1, 0},   {0, -1, 0},
    {0, 0, 1},   {0, 0, -1},  {1, 1, 0},  {-1, -1, 0}, {1, 0, 1},
    {-1, 0, -1}, {0, 1, 1},   {0, -1, -1}, {1, -1, 0}, {-1, 1, 0},
    {1, 0, -1},  {-1, 0, 1},  {0, 1, -1}, {0, -1, 1}};

const double kW[19] = {
    1.0 / 3.0,  1.0 / 18.0, 1.0 / 18.0, 1.0 / 18.0, 1.0 / 18.0, 1.0 / 18.0,
    1.0 / 18.0, 1.0 / 36.0, 1.0 / 36.0, 1.0 / 36.0, 1.0 / 36.0, 1.0 / 36.0,
    1.0 / 36.0, 1.0 / 36.0, 1.0 / 36.0, 1.0 / 36.0, 1.0 / 36.0, 1.0 / 36.0,
    1.0 / 36.0};

double reference(int k, double rho, const double* u) {
  double u2 = u[0] * u[0] + u[1] * u[1] + u[2] * u[2];
  double uc = u[0] * kC[k][0] + u[1] * kC[k][1] + u[2] * kC[k][2];
  return kW[k] * rho *
         (1.0 + 3.0 * uc + uc * uc * 0.5 * 9.0 - 3.0 * u2 * 0.5);
}

}  // namespace

int main() {
  const double rho = 1.3;
  const double uv[3] = {0.05, -0.02, 0.031};

  Vector<double, 3> u;
  u[0] = uv[0];
  u[1] = uv[1];
  u[2] = uv[2];

  double feq[19];
  equilibrium_d3q19(feq, rho, u);

  double maxErr = 0.0;
  for (int k = 0; k < 19; ++k) {
    double err = std::fabs(feq[k] - reference(k, rho, uv));
    if (err > maxErr) maxErr = err;
  }

  std::printf("max abs error = %.3e\n", maxErr);

  // The emitted weights are declared accessors, so they evaluate exactly to
  // the lattice definition for any FloatType (no baked decimal literals).
  bool weightsOk =
      latset::w<D3Q19<double>>(1) == (1.0 / 18.0) &&
      latset::w<D3Q19<double>>(7) == (1.0 / 36.0) &&
      latset::w<D3Q19<float>>(1) ==
          (static_cast<float>(1) / static_cast<float>(18));
  std::printf("declared weight accessors preserved: %s\n",
              weightsOk ? "yes" : "no");

  return (maxErr < 1e-12 && weightsOk) ? 0 : 1;
}
